import fs from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const siteDataPath = path.join(projectRoot, "src", "data", "siteData.js");

const { aboutContent } = await import(pathToFileURL(siteDataPath));

const htmlToMarkdown = (html) => {
  if (!html) return "";

  let output = html;

  // Convert links: <a href="...">text</a> -> text (url)
  output = output.replace(
    /<a [^>]*href="([^"]+)"[^>]*>(.*?)<\/a>/gi,
    "$2 ($1)"
  );
  // Convert headings to markdown equivalents
  output = output.replace(/<h1[^>]*>(.*?)<\/h1>/gi, "# $1\n\n");
  output = output.replace(/<h2[^>]*>(.*?)<\/h2>/gi, "## $1\n\n");
  output = output.replace(/<h3[^>]*>(.*?)<\/h3>/gi, "### $1\n\n");
  // Handle breaks and block-level tags
  output = output.replace(/<br\s*\/?>/gi, "\n");
  output = output.replace(/<\/(p|div)>/gi, "\n\n");
  output = output.replace(/<(p|div)[^>]*>/gi, "");
  // Strip any remaining tags
  output = output.replace(/<[^>]+>/g, "");
  // Collapse excessive blank lines
  output = output.replace(/\n{3,}/g, "\n\n");

  return output.trim();
};

const aboutMarkdown = htmlToMarkdown(aboutContent);

const readme = `# Rohan Verma — Personal Website

${aboutMarkdown}

## Tech Stack
- React 19 with React Router 7 for client-side routing.
- Vite 7 for dev server and production builds.
- Framer Motion for page transition animations.
- Plain CSS plus a streaming-text component (\`StreamResponse\`) for staged rendering of HTML content.
- npm for scripts; ESLint for linting.

## Running the Site Locally
- Requirements: Node.js 18+ and npm.
- Install dependencies: \`npm install\`
- Start dev server: \`npm run dev\` (opens via Vite on the port it selects).
- Lint: \`npm run lint\`
- Production build: \`npm run build\`
- Preview the build: \`npm run preview\`

## Project Layout
- \`src/data/siteData.js\` — Bio, experience, projects, and social links.
- \`src/pages/\` — Route-level pages (\`About.jsx\`, \`Experience.jsx\`, \`Projects.jsx\`).
- \`src/components/\` — Shared UI (page transitions, streaming response renderer, etc.).
- \`dist/\` — Production build output generated by \`npm run build\`.

---
Generated by \`npm run generate:readme\`. Update \`siteData.aboutContent\` to change this section and rerun the script.
`;

const readmePath = path.join(projectRoot, "README.md");
fs.writeFileSync(readmePath, `${readme.trim()}\n`);
console.log("README.md refreshed from siteData.aboutContent");
